/**
 * Character_Framework.md (v2.1) 的选项常量
 */

const nsfwAttributeOptions = [
  { level: '', label: '是', description: '为该角色生成可选的“NSFW属性”模块。', value: 'true' },
  { level: '', label: '否', description: '不生成NSFW属性。', value: 'false' },
];

export const CHARACTER_OPTIONS = {
  globals: {},
  pc: {
    enable_nsfw_attributes: nsfwAttributeOptions,
    template_level: [
      { level: '', label: '---', description: '请选择模板等级。', value: '' },
      {
        level: '1',
        label: '核心概念',
        description: '极简起点。仅定义一句话核心概念，几乎完全自由。',
        value: '核心概念 (等级1)',
      },
      {
        level: '2',
        label: '基础骨架',
        description: '轮廓鲜明。拥有核心概念、身份和标志性外观。',
        value: '基础骨架 (等级2)',
      },
      {
        level: '3',
        label: '标准档案',
        description: '背景锚点。拥有具体的过去、核心矛盾和初始社会关系。',
        value: '标准档案 (等级3)',
      },
      {
        level: '4',
        label: '深度剖析',
        description: '深度角色。包含复杂的内在机制、能力和人际关系动态。',
        value: '深度剖析 (等级4)',
      },
      {
        level: '5',
        label: '完整卷宗',
        description: '活态历史。拥有极其详尽的背景、行为模式和感官特征。',
        value: '完整卷宗 (等级5)',
      },
    ],
  },
  key: {
    enable_nsfw_attributes: nsfwAttributeOptions,
    template_level: [
      { level: '', label: '---', description: '请选择模板等级。', value: '' },
      {
        level: '2',
        label: '基础骨架',
        description: '轮廓鲜明。拥有核心概念、身份和标志性外观。',
        value: '基础骨架 (等级2)',
      },
      {
        level: '3',
        label: '标准档案',
        description: '背景锚点。拥有具体的过去、核心矛盾和初始社会关系。',
        value: '标准档案 (等级3)',
      },
      {
        level: '4',
        label: '深度剖析',
        description: '深度角色。包含复杂的内在机制、能力和人际关系动态。',
        value: '深度剖析 (等级4)',
      },
      {
        level: '5',
        label: '完整卷宗',
        description: '活态历史。拥有极其详尽的背景、行为模式和感官特征。',
        value: '完整卷宗 (等级5)',
      },
    ],
    // --- 新增角色属性 ---
    relational_proximity_options: [
      { label: '---', description: '请选择角色与核心的社交距离。', value: '' },
      { label: '亲密层', description: '共享秘密、情感高度卷入的个体（如：爱人、家人、宿敌）。', value: 'intimate' },
      { label: '社交层', description: '有固定社会关系，但存在情感距离（如：同事、老师、盟友）。', value: 'social' },
      {
        label: '交易层',
        description: '基于特定需求产生交集，关系通常有明确目的（如：情报商、任务发布人）。',
        value: 'transactional',
      },
      {
        label: '外部层',
        description: '故事背景的一部分，无直接私人关系（如：传说中的英雄、敌国君主）。',
        value: 'external',
      },
    ],
    social_class_options: [
      { label: '---', description: '请选择角色的核心社会阶层。', value: '' },
      {
        label: '下层阶级',
        description: '生活在社会底层，资源匮乏，为生计挣扎（如：奴隶、贫民、流浪者）。',
        value: 'lower_class',
      },
      {
        label: '劳动阶级',
        description: '依靠体力或技能劳动为生，构成社会基础（如：农民、工匠、士兵）。',
        value: 'working_class',
      },
      {
        label: '中产阶级',
        description: '拥有一定资产或专业知识，生活相对稳定（如：商人、医生、学者）。',
        value: 'middle_class',
      },
      {
        label: '上层阶级',
        description: '拥有显著财富或社会地位，但非权力核心（如：大商人、小贵族、名流）。',
        value: 'upper_class',
      },
      {
        label: '统治阶级',
        description: '掌握政治、军事或宗教权力，处于社会顶端（如：王族、高级官员、大祭司）。',
        value: 'ruling_class',
      },
      {
        label: '边缘/化外之人',
        description: '处于主流社会结构之外，不受其规则约束（如：隐士、法外之徒、异族）。',
        value: 'outsider',
      },
    ],
    thematic_role_options: [
      { label: '---', description: '（可选）请选择角色的主要主题作用。', value: '' },
      { label: '--- 浪漫/情感 ---', description: '', value: 'heading_romance', disabled: true },
      { label: '浪漫引力核心', description: '作为故事主要的恋爱/情感对象。', value: 'romance_core' },
      { label: '情感支持锚点', description: '提供安慰、理解和情感支持的“安全港”。', value: 'emotional_anchor' },
      { label: '关系考验者', description: '考验、介入或试图破坏核心情感关系的角色。', value: 'relationship_tester' },
      { label: '--- 冲突/悬疑 ---', description: '', value: 'heading_conflict', disabled: true },
      { label: '核心冲突源', description: '作为故事的主要对手、反派或障碍。', value: 'conflict_source' },
      { label: '麻烦制造者', description: '不可预测，为故事带来意外事件或混乱。', value: 'troublemaker' },
      { label: '秘密持有者', description: '掌握关键信息或秘密，制造悬念和推动调查。', value: 'secret_keeper' },
      { label: '--- 日常/成长 ---', description: '', value: 'heading_growth', disabled: true },
      { label: '日常陪伴者', description: '共同经历生活点滴，塑造日常氛围的核心人物。', value: 'daily_companion' },
      { label: '人生导师', description: '在技能、知识或精神上提供引导和教诲。', value: 'mentor' },
      { label: '成长催化剂', description: '像一面镜子，其存在或行为激发主角反思和成长。', value: 'growth_catalyst' },
      { label: '--- NSFW/情欲 ---', description: '', value: 'heading_nsfw', disabled: true },
      { label: '情欲唤醒者', description: '作为故事主要的性吸引力或情欲探索的对象。', value: 'erotic_awakener' },
      { label: '权力游戏对手', description: '在BDSM等权力动态关系中扮演关键角色。', value: 'power_play_partner' },
      { label: '禁忌探索者', description: '引导或共同探索超越常规或禁忌的关系/行为。', value: 'taboo_explorer' },
      { label: '--- 喜剧/氛围 ---', description: '', value: 'heading_comedy', disabled: true },
      { label: '喜剧调剂品', description: '负责搞笑、缓和气氛或提供讽刺性评论。', value: 'comic_relief' },
      {
        label: '世界解说员',
        description: '通过其言行举止，自然地向玩家展示世界观和背景设定。',
        value: 'world_expositor',
      },
    ],
    psychological_profile: {
      openness: [
        { value: '', level: '0/7', label: '---', description: '未指定此项人格特质。' },
        {
          value: '务实传统派',
          level: '1/7',
          label: '务实传统派',
          description: '注重实际、偏爱常规、脚踏实地，对抽象理论不感兴趣。',
        },
        {
          value: '谨慎接纳者',
          level: '2/7',
          label: '谨慎接纳者',
          description: '对新事物持保留态度，但经过验证后可以接受。',
        },
        {
          value: '温和探索者',
          level: '3/7',
          label: '温和探索者',
          description: '对新思想有一定兴趣，但不会主动寻求颠覆性体验。',
        },
        {
          value: '平衡思考者',
          level: '4/7',
          label: '平衡思考者',
          description: '在现实与想象之间取得平衡，既有好奇心也重实用。',
        },
        { value: '创意爱好者', level: '5/7', label: '创意爱好者', description: '乐于接受新思想和艺术，享受多样性。' },
        { value: '高度好奇者', level: '6/7', label: '高度好奇者', description: '富有想象力，主动寻求新奇体验和知识。' },
        {
          value: '艺术幻想家',
          level: '7/7',
          label: '艺术幻想家',
          description: '极富想象、拥抱新奇、不切实际，活在自己的世界里。',
        },
      ],
      conscientiousness: [
        { value: '', level: '0/7', label: '---', description: '未指定此项人格特质。' },
        {
          value: '随性艺术家',
          level: '1/7',
          label: '随性艺术家',
          description: '冲动、随性、不拘小节，讨厌计划和束缚。',
        },
        {
          value: '灵活应变者',
          level: '2/7',
          label: '灵活应变者',
          description: '不太喜欢计划，但能完成短期任务，偏好灵活。',
        },
        { value: '任务导向者', level: '3/7', label: '任务导向者', description: '能够完成任务，但过程可能缺乏条理。' },
        { value: '可靠执行者', level: '4/7', label: '可靠执行者', description: '有责任心，能够可靠地完成分内之事。' },
        { value: '高效组织者', level: '5/7', label: '高效组织者', description: '做事有条理，注重效率和自我约束。' },
        { value: '自律追求者', level: '6/7', label: '自律追求者', description: '高度自律，有强烈的责任感和成就动机。' },
        {
          value: '完美规划师',
          level: '7/7',
          label: '完美规划师',
          description: '极度自律、有条不紊、追求完美，有时显得刻板。',
        },
      ],
      extraversion: [
        { value: '', level: '0/7', label: '---', description: '未指定此项人格特质。' },
        { value: '独处思考者', level: '1/7', label: '独处思考者', description: '安静、内省、审慎，在独处中恢复能量。' },
        { value: '宁静观察者', level: '2/7', label: '宁静观察者', description: '话不多，喜欢观察多于参与。' },
        { value: '慢热交往者', level: '3/7', label: '慢热交往者', description: '在熟悉的环境和人面前才会变得健谈。' },
        {
          value: '选择性社交者',
          level: '4/7',
          label: '选择性社交者',
          description: '既能享受独处，也能在喜欢的社交场合中游刃有余。',
        },
        { value: '积极参与者', level: '5/7', label: '积极参与者', description: '喜欢社交活动，能够轻松与人交往。' },
        { value: '热情健谈者', level: '6/7', label: '热情健谈者', description: '精力充沛，健谈，主动发起社交。' },
        {
          value: '社交核心',
          level: '7/7',
          label: '社交核心',
          description: '极度外向，是人群的焦点，在社交中获得巨大能量。',
        },
      ],
      agreeableness: [
        { value: '', level: '0/7', label: '---', description: '未指定此项人格特质。' },
        {
          value: '锐利批评家',
          level: '1/7',
          label: '锐利批评家',
          description: '多疑、有竞争性、直言不讳，为了目标不惜引发冲突。',
        },
        {
          value: '务实竞争者',
          level: '2/7',
          label: '务实竞争者',
          description: '以自我利益为中心，合作是出于策略而非本性。',
        },
        { value: '独立主张者', level: '3/7', label: '独立主张者', description: '有自己的想法，不会轻易附和他人。' },
        {
          value: '公平合作者',
          level: '4/7',
          label: '公平合作者',
          description: '通情达理，愿意合作，但也会坚持自己的权利。',
        },
        {
          value: '热心帮助者',
          level: '5/7',
          label: '热心帮助者',
          description: '乐于助人，通常信任他人，关心他人感受。',
        },
        {
          value: '富有同情心者',
          level: '6/7',
          label: '富有同情心者',
          description: '有强烈的同理心，总是先为他人着想。',
        },
        {
          value: '和谐维护者',
          level: '7/7',
          label: '和谐维护者',
          description: '极富同情心、信任他人，会不惜一切代价避免冲突。',
        },
      ],
      neuroticism: [
        { value: '', level: '0/7', label: '---', description: '未指定此项人格特质。' },
        {
          value: '沉稳磐石',
          level: '1/7',
          label: '沉稳磐石',
          description: '情绪稳定、沉着、抗压性强，不易感到焦虑或沮丧。',
        },
        {
          value: '冷静应对者',
          level: '2/7',
          label: '冷静应对者',
          description: '大多数情况下保持冷静，偶尔会感到压力。',
        },
        {
          value: '偶有波澜者',
          level: '3/7',
          label: '偶有波澜者',
          description: '情绪总体稳定，但在特定压力下会显露担忧。',
        },
        {
          value: '中度敏感者',
          level: '4/7',
          label: '中度敏感者',
          description: '情绪有正常起伏，能感受到压力但也能应对。',
        },
        { value: '易受影响者', level: '5/7', label: '易受影响者', description: '情绪容易受外界影响，时常感到担忧。' },
        {
          value: '高度焦虑者',
          level: '6/7',
          label: '高度焦虑者',
          description: '经常感到紧张和焦虑，容易将小事看得很重。',
        },
        {
          value: '敏感诗人',
          level: '7/7',
          label: '敏感诗人',
          description: '情绪波动极大、极度敏感、焦虑，长期处于负面情绪中。',
        },
      ],
    },
    core_values: {
      care: [
        { label: '---', description: '请选择角色在此维度的倾向', value: '' },
        { label: '1/7: 冷酷功利者', description: '“情感是弱点，只有结果才重要。”', value: 'care_1' },
        { label: '2/7: 漠然旁观者', description: '“别人的痛苦与我无关，我只关心自己的生存。”', value: 'care_2' },
        { label: '3/7: 有限同情者', description: '“我只关心我的亲友，陌生人的死活我不在乎。”', value: 'care_3' },
        { label: '4/7: 常识共情者', description: '“我不想看到无辜者受苦，但也不会为此牺牲太多。”', value: 'care_4' },
        { label: '5/7: 善良帮助者', description: '“看到别人受难，我总会忍不住伸出援手。”', value: 'care_5' },
        { label: '6/7: 坚定守护者', description: '“保护弱小是我的责任，我会主动对抗不公。”', value: 'care_6' },
        { label: '7/7: 无私奉献者', description: '“我愿意牺牲自己，来终结他人的痛苦。”', value: 'care_7' },
      ],
      fairness: [
        { label: '---', description: '请选择角色在此维度的倾向', value: '' },
        {
          label: '1/7: 彻底的利己主义者',
          description: '“规则就是用来打破的，我只信奉我自己的利益。”',
          value: 'fairness_1',
        },
        {
          label: '2/7: 投机取巧者',
          description: '“只要不被发现，用点小手段达成目的没什么大不了。”',
          value: 'fairness_2',
        },
        {
          label: '3/7: 双标维护者',
          description: '“我要求别人公平待我，但我自己可以为了赢而不择手段。”',
          value: 'fairness_3',
        },
        { label: '4/7: 契约精神者', description: '“我遵守明确的规则和契约，这是合作的基础。”', value: 'fairness_4' },
        { label: '5/7: 公正支持者', description: '“我追求对等的合作关系，厌恶欺诈和不公。”', value: 'fairness_5' },
        {
          label: '6/7: 秩序维护者',
          description: '“我不仅自己遵守，还会主动站出来维护规则的公正。”',
          value: 'fairness_6',
        },
        {
          label: '7/7: 绝对平等主义者',
          description: '“我追求绝对的公平，任何形式的特权都不可接受。”',
          value: 'fairness_7',
        },
      ],
      loyalty: [
        { label: '---', description: '请选择角色在此维度的倾向', value: '' },
        { label: '1/7: 孤狼', description: '“我谁都不信，只忠于自己。”', value: 'loyalty_1' },
        { label: '2/7: 机会主义盟友', description: '“我和你一伙，只是因为我们有共同的敌人。”', value: 'loyalty_2' },
        {
          label: '3/7: 实用主义伙伴',
          description: '“我的忠诚有价码，更高的利益出现时我会重新考虑。”',
          value: 'loyalty_3',
        },
        { label: '4/7: 可靠的团队成员', description: '“我信守对团队的承诺，不会轻易背叛。”', value: 'loyalty_4' },
        {
          label: '5/7: 坚定的拥护者',
          description: '“我对我所属的团体（家庭/组织）有强烈的归属感。”',
          value: 'loyalty_5',
        },
        {
          label: '6/7: 狂热的信徒',
          description: '“为了我的集体，我愿意付出一切，背叛者必须受到严惩。”',
          value: 'loyalty_6',
        },
        {
          label: '7/7: 集体意志化身',
          description: '“我就是集体，集体的利益高于一切，包括我个人的生命。”',
          value: 'loyalty_7',
        },
      ],
      authority: [
        { label: '---', description: '请选择角色在此维度的倾向', value: '' },
        { label: '1/7: 天生的反叛者', description: '“所有权威都是压迫的工具，必须被摧毁。”', value: 'authority_1' },
        { label: '2/7: 质疑者', description: '“我不相信任何官方说法，除非我亲眼所见。”', value: 'authority_2' },
        {
          label: '3/7: 规则的变通者',
          description: '“我尊重权威，但如果规则不合理，我会绕过它。”',
          value: 'authority_3',
        },
        { label: '4/7: 守序的公民', description: '“我相信一个稳定的社会需要秩序和层级。”', value: 'authority_4' },
        { label: '5/7: 传统的拥护者', description: '“我尊重传统和领导者，他们是智慧的结晶。”', value: 'authority_5' },
        {
          label: '6/7: 秩序的捍卫者',
          description: '“挑战权威就是挑战稳定，我会坚决制止这种行为。”',
          value: 'authority_6',
        },
        { label: '7/7: 绝对的服从者', description: '“上级的命令就是一切，我不会有任何质疑。”', value: 'authority_7' },
      ],
      sanctity: [
        { label: '---', description: '请选择角色在此维度的倾向', value: '' },
        {
          label: '1/7: 百无禁忌者',
          description: '“没有什么东西是神圣的，肉体和精神都只是工具。”',
          value: 'sanctity_1',
        },
        { label: '2/7: 享乐主义者', description: '“我追求感官的极致体验，不在乎世俗的眼光。”', value: 'sanctity_2' },
        {
          label: '3/7: 实用主义者',
          description: '“我没有特别的禁忌，只要能达成目的，任何手段都可以。”',
          value: 'sanctity_3',
        },
        {
          label: '4/7: 世俗的普通人',
          description: '“我有一些自己的底线，但对别人的生活方式不予置评。”',
          value: 'sanctity_4',
        },
        {
          label: '5/7: 精神追求者',
          description: '“我相信有些东西是神圣不可侵犯的，比如灵魂、信仰或自然。”',
          value: 'sanctity_5',
        },
        {
          label: '6/7: 纯洁的守护者',
          description: '“我努力保持身心的纯洁，并厌恶那些堕落和亵渎的行为。”',
          value: 'sanctity_6',
        },
        {
          label: '7/7: 苦行僧/圣徒',
          description: '“我通过严苛的戒律来净化我的灵魂，追求至高的神圣。”',
          value: 'sanctity_7',
        },
      ],
      liberty: [
        { label: '---', description: '请选择角色在此维度的倾向', value: '' },
        { label: '1/7: 绝对的控制者', description: '“所有人都应该按我的意志行事，为了他们好。”', value: 'liberty_1' },
        { label: '2/7: 支配者', description: '“我喜欢掌控局面的感觉，别人的服从让我满足。”', value: 'liberty_2' },
        { label: '3/7: 精英主义者', description: '“我认为强者或智者理应领导和支配他人。”', value: 'liberty_3' },
        {
          label: '4/7: 务实的个人主义者',
          description: '“我追求自己的自由，但不会主动为别人的自由而战。”',
          value: 'liberty_4',
        },
        { label: '5/7: 自由的同情者', description: '“我无法忍受看到别人被欺凌和压迫。”', value: 'liberty_5' },
        { label: '6/7: 解放者', description: '“我会主动帮助他人摆脱压迫，争取自由。”', value: 'liberty_6' },
        {
          label: '7/7: 自由意志的捍卫者',
          description: '“不自由，毋宁死。任何形式的奴役都必须被终结。”',
          value: 'liberty_7',
        },
      ],
    },
  },
  supporting: {
    enable_nsfw_attributes: nsfwAttributeOptions,
    template_level: [
      { level: '', label: '---', description: '请选择模板等级。', value: '' },
      { level: '1', label: '核心概念', description: '极简起点。仅定义一句话核心概念。', value: '核心概念 (等级1)' },
      {
        level: '2',
        label: '基础骨架',
        description: '轮廓鲜明。拥有核心概念、身份和标志性外观。',
        value: '基础骨架 (等级2)',
      },
      {
        level: '3',
        label: '标准档案',
        description: '背景锚点。拥有具体的过去、核心矛盾和初始社会关系。',
        value: '标准档案 (等级3)',
      },
    ],
    role_focus_counts: [
        { label: '目标提供者', description: '涵盖任务发布人、求助者，或自身成为需要帮助/拯救的目标的角色，专注于“驱动玩家行动”。' },
        { label: '信息与秘密持有者', description: '整合情报商和世界解说员，专注于提供世界观、剧情线索、角色秘密等信息。' },
        { label: '服务与资源提供者', description: '包含商人、医生、工匠、向导等所有能为玩家提供具体帮助或物品的角色。' },
        { label: '冲突与障碍制造者', description: '包括竞争对手、小规模敌人、制造麻烦的官僚等，提供直接的挑战。' },
        { label: '派系与组织代表', description: '作为某个组织（国家、公会、密谋）的代表，是连接玩家与宏大叙事的关键。' },
        { label: '社交与氛围营造者', description: '没有明确功能，但能让世界更生动、提供日常互动机会的角色（如酒馆老板、吟游诗人）。' },
    ],
  },
  ambient: {
    enable_nsfw_attributes: nsfwAttributeOptions,
    template_level: [
      { level: '', label: '---', description: '请选择模板等级。', value: '' },
      { level: '1', label: '核心概念', description: '极简起点。仅定义一句话核心概念。', value: '核心概念 (等级1)' },
      {
        level: '2',
        label: '基础骨架',
        description: '轮廓鲜明。拥有核心概念、身份和标志性外观。',
        value: '基础骨架 (等级2)',
      },
    ],
    group_counts: [
        { label: '平民阶层', description: '构成社会基础的劳动者，是任何世界不可或缺的背景板。' },
        { label: '统治阶层', description: '涵盖贵族、官员、士兵、卫兵等所有掌握权力的个体，体现完整的权力结构。' },
        { label: '商业与行会', description: '从事交易和流通的商人、小贩、以及各类行会，代表社会的经济活力。' },
        { label: '信仰与学术团体', description: '包括祭司、信徒、学者、法师等，表现世界的精神与智识层面。' },
        { label: '法外与边缘群体', description: '包括罪犯、帮派，也包括不被主流社会接纳的隐士、异端、流亡者等。' },
        { label: '流动人口', description: '包括佣兵、冒险家、难民、朝圣者、商队等，是信息、冲突和机遇的传播者。' },
    ],
  },
};
