/**
 * PlayerNeeds_Framework.md (v3.6) 的选项常量
 */
import { GradientOption } from '../types/AppTypes';

export const BLANK_GRADIENT_OPTION: GradientOption = {
  level: '',
  label: '---',
  description: '请选择一个选项',
  value: '',
};

const createGradient = (level: number, label: string, description: string) => ({
  level: `${level}/7`,
  label,
  description,
  value: `${level}/7: ${description}`,
});

const createFocusGradient = (level: number, label: string, description: string) => ({
  level: `${level}/4`,
  label,
  description,
  value: `${level}/4: ${description}`,
});

export const NEEDS_OPTIONS = {
  emotion: {
    points: [
      { label: '浪漫/亲密关系', description: '体验角色间的情感连接、依赖和羁绊。' },
      { label: '情欲/性吸引力', description: '体验角色间的欲望、张力与身体吸引力。' },
      { label: '成就/个人成长', description: '体验克服挑战、获得力量或实现自我。' },
      { label: '慰藉/情感支持', description: '体验被理解、被治愈或守护他人的温暖。' },
      { label: '惊险/紧张感', description: '体验心跳加速的刺激、悬疑和危险。' },
      { label: '负面情感宣泄', description: '体验悲伤、痛苦、遗憾等强烈负面情绪并得以释放。' },
      { label: '探索/揭示秘密', description: '体验发现未知、解开谜团、了解真相的乐趣。' },
      { label: '幽默/喜剧性', description: '体验轻松、愉快、荒诞或讽刺带来的欢笑。' },
    ],
    flavor_descriptions: {
      '浪漫/亲密关系': '甜蜜日常 vs. 虐心纠葛',
      '情欲/性吸引力': '原始本能 vs. 高阶挑逗',
      '成就/个人成长': '外部征服 vs. 自我成长',
      '慰藉/情感支持': '被动受呵护 vs. 相互支持治愈',
      '惊险/紧张感': '心理悬疑惊悚 vs. 动作场面刺激',
      负面情感宣泄: '宿命悲剧 vs. 忧郁美学',
      '探索/揭示秘密': '探索世界奥秘 vs. 挖掘角色秘密',
      '幽默/喜剧性': '无厘头荒诞 vs. 智慧讽刺',
    },
    flavors: {
      '浪漫/亲密关系': [
        BLANK_GRADIENT_OPTION,
        createGradient(1, '纯粹甜蜜', '只有温馨日常，无冲突。'),
        createGradient(2, '轻度波折', '小误会是感情增进剂。'),
        createGradient(3, '温情主导', '甜蜜为主，伴有严肃挑战。'),
        createGradient(4, '甜虐均衡', '甜蜜与痛苦深刻交织。'),
        createGradient(5, '纠葛主导', '障碍重重，甜蜜是短暂慰藉。'),
        createGradient(6, '深度虐心', '持续的巨大痛苦、误解、分离。'),
        createGradient(7, '纯粹悲剧', '关系注定悲剧收场。'),
      ],
      '情欲/性吸引力': [
        BLANK_GRADIENT_OPTION,
        createGradient(1, '极致挑逗', '精神引诱，极少身体接触。'),
        createGradient(2, '感官游戏', '侧重缓慢、充满张力的感官探索。'),
        createGradient(3, '浪漫激情', '欲望与情感深度融合。'),
        createGradient(4, '平衡欲望', '兼具情感连接与肉体吸引力。'),
        createGradient(5, '强烈冲动', '欲望强烈，侧重即时满足。'),
        createGradient(6, '原始本能', '接近动物性的、不加掩饰的本能。'),
        createGradient(7, '极致野性', '纯粹由原始本能主导。'),
      ],
      '成就/个人成长': [
        BLANK_GRADIENT_OPTION,
        createGradient(1, '纯粹外部征服', '来自战胜敌人、积累财富等外在胜利。'),
        createGradient(2, '目标驱动型成就', '来自完成宏大、困难的外部目标。'),
        createGradient(3, '技艺与知识精通', '来自成为某个领域的大师。'),
        createGradient(4, '内外平衡的成长', '克服外部挑战，实现心性与能力同步成长。'),
        createGradient(5, '克服内心障碍', '来自战胜自身的恐惧、创伤或缺陷。'),
        createGradient(6, '建立深刻联结', '来自于建立或维系深刻的人际关系。'),
        createGradient(7, '纯粹自我实现', '来自对“我是谁”的终极探索。'),
      ],
      '慰藉/情感支持': [
        BLANK_GRADIENT_OPTION,
        createGradient(1, '绝对被动', '纯粹的被保护、被照顾对象。'),
        createGradient(2, '被动为主', '主要被照顾，偶尔提供支持。'),
        createGradient(3, '情感避风港', '主要寻求慰藉，关系基于情感依赖。'),
        createGradient(4, '平衡互助', '双方对等地相互治愈。'),
        createGradient(5, '主动关怀', '通过照顾他人获得慰藉。'),
        createGradient(6, '相互支撑', '像战友在困境中相互扶持。'),
        createGradient(7, '拯救者角色', '作为唯一的守护者，从拯救他人中获得满足。'),
      ],
      '惊险/紧张感': [
        BLANK_GRADIENT_OPTION,
        createGradient(1, '纯粹悬疑', '紧张感来自未知、心理压力和氛围。'),
        createGradient(2, '惊悚为主', '侧重心理恐惧和智斗。'),
        createGradient(3, '潜行解谜', '紧张感来自规避危险、解谜求生。'),
        createGradient(4, '冒险求生', '平衡探索、资源管理与应对危险。'),
        createGradient(5, '动作冒险', '以惊险动作场面为主。'),
        createGradient(6, '激烈战斗', '紧张感主要来源于高强度战斗追逐。'),
        createGradient(7, '纯粹动作', '叙事为动作场面服务，追求感官冲击。'),
      ],
      负面情感宣泄: [
        BLANK_GRADIENT_OPTION,
        createGradient(1, '纯粹忧郁', '体验一种挥之不去的优美伤感。'),
        createGradient(2, '伤感怀旧', '情感来自对逝去美好的追忆。'),
        createGradient(3, '遗憾美学', '由错误选择或错过导致的长期痛苦。'),
        createGradient(4, '创伤后治愈', '宣泄来自克服或接受过去的创伤。'),
        createGradient(5, '激烈牺牲', '通过重大的、有意义的牺牲达到高潮。'),
        createGradient(6, '宿命悲剧', '角色抗争但终究无法摆脱悲剧宿命。'),
        createGradient(7, '毁灭性崩溃', '宣泄来自于经历或目睹彻底的崩溃。'),
      ],
      '探索/揭示秘密': [
        BLANK_GRADIENT_OPTION,
        createGradient(1, '纯粹世界', '只关注宏大的世界历史、地理、魔法体系。'),
        createGradient(2, '遗迹考古', '通过探索古代遗迹揭示世界历史。'),
        createGradient(3, '环境叙事', '通过环境细节拼凑故事。'),
        createGradient(4, '关联探索', '角色秘密与世界奥秘紧密相连。'),
        createGradient(5, '人物调查', '通过交谈和线索揭示他人秘密。'),
        createGradient(6, '关系深掘', '通过与关键角色建立深度关系了解其内心。'),
        createGradient(7, '纯粹内心', '完全聚焦于挖掘核心角色的深层心理秘密。'),
      ],
      '幽默/喜剧性': [
        BLANK_GRADIENT_OPTION,
        createGradient(1, '纯粹智慧', '幽默来自精妙的语言、讽刺和智力交锋。'),
        createGradient(2, '情景喜剧', '幽默来自角色在特定情境中的反应。'),
        createGradient(3, '黑色幽默', '从悲剧、禁忌或严肃话题中寻找笑点。'),
        createGradient(4, '荒诞幽默', '平衡语言梗和超现实情景。'),
        createGradient(5, '无厘头', '幽默来自夸张的肢体动作和不合逻辑的行为。'),
        createGradient(6, '超现实主义', '幽默来自打破现实逻辑的梦境般设定。'),
        createGradient(7, '纯粹胡闹', '完全放弃逻辑，追求极致的混乱胡闹。'),
      ],
    },
  },
  power: {
    // 全局关系设定
    objective_spectrum: [
      BLANK_GRADIENT_OPTION,
      createGradient(1, '绝对从属', '权力完全被剥夺，无任何自主决策权，必须服从。'),
      createGradient(2, '下位', '权力处于明显劣势，行动需获批准或遵循指令。'),
      createGradient(3, '被动对等', '权力对等，但通常是被动响应方，由对方主导互动。'),
      createGradient(4, '动态对等', '权力对等，支配地位在双方间动态流动。'),
      createGradient(5, '主动对等', '权力对等，但通常是主动发起方，主导互动进程。'),
      createGradient(6, '上位', '权力处于明显优势，能够主导或否决对方的行动。'),
      createGradient(7, '绝对支配', '拥有绝对权威，能够单方面制定规则和下达命令。'),
    ],
    dominant_party: [
      BLANK_GRADIENT_OPTION,
      {
        level: '1/4',
        label: '主控角色(PC)为主支配方',
        description: '权力关系由玩家主导，NPC多为响应或顺从方。',
        value: '1/4: 主控角色(PC)为主支配方',
      },
      {
        level: '2/4',
        label: '重要角色(NPC)为主支配方',
        description: '权力关系由NPC主导，玩家多为响应或顺从方。',
        value: '2/4: 重要角色(NPC)为主支配方',
      },
      {
        level: '3/4',
        label: '动态交换/双方均可',
        description: '支配地位不固定，在双方之间流动，形成博弈或伙伴关系。',
        value: '3/4: 动态交换/双方均可',
      },
      {
        level: '4/4',
        label: '第三方/环境为主支配方',
        description:
          '真正的支配力量来自外部（如：严苛的社会制度、共同的敌人、恶劣的自然环境），PC与NPC的关系在共同的外部压力下展开。',
        value: '4/4: 第三方/环境为主支配方',
      },
    ],
    dominant_power_sources_points: [
      { label: '武力/破坏力', description: '通过物理、魔法、科技等手段直接造成伤害或施加物理影响的能力。' },
      { label: '权威/合法性', description: '源自法律、社会规范、神授权利或既定等级制度的公认权力。' },
      { label: '资源控制', description: '掌控金钱、土地、食物、能源、技术设备等关键物质或非物质资源。' },
      { label: '信息/知识优势', description: '因拥有秘密、掌握专门知识（如奥术、科技）或控制信息渠道而带来的权力。' },
      { label: '精神/意志操纵', description: '通过情感、心智、信仰或超自然方式影响或控制他人的思想、情绪和行为。' },
      { label: '潜在威胁', description: '未明确展示但确实存在的、足以让对方忌惮的报复或伤害能力。' },
    ],
    expression_spectrum: [
      BLANK_GRADIENT_OPTION,
      createGradient(1, '完全隐秘', '权力完全隐藏，通过暗示行使。'),
      createGradient(2, '暗中影响', '权力不公开讨论，但对方能明确感觉。'),
      createGradient(3, '非正式权力', '权力是公认的潜规则。'),
      createGradient(4, '混合表达', '部分权力正式，部分隐藏。'),
      createGradient(5, '官方授权', '有明确职位，但行使时有裁量权。'),
      createGradient(6, '制度化权力', '由法律、规则明确界定和保障。'),
      createGradient(7, '绝对公开', '公开宣告、不容置疑的权力。'),
    ],
    importance_spectrum: [
      BLANK_GRADIENT_OPTION,
      createGradient(1, '历史尘埃', '无名小卒，对世界无影响。'),
      createGradient(2, '旁观者', '能见证大事件，但无法影响。'),
      createGradient(3, '参与者', '能影响局部战局或事件。'),
      createGradient(4, '关键人物', '决定能显著影响一个地区或重要事件。'),
      createGradient(5, '时代推手', '推动历史进程的关键力量之一。'),
      createGradient(6, '世界支点', '世界的命运系于玩家一身。'),
      createGradient(7, '天选之子', '世界规则与命运围绕玩家展开。'),
    ],

    // PC & NPC 动态选项
    interaction_strategy_spectrum: [
      BLANK_GRADIENT_OPTION,
      createGradient(1, '顺应退让', '主动迎合对方意愿以避免冲突，或在劣势下完全服从。'),
      createGradient(2, '迂回影响', '表面合作，但通过暗示、引导等间接方式影响对方决策。'),
      createGradient(3, '协商博弈', '寻求共同点，通过平等对话、交换条件和互相让步来解决分歧。'),
      createGradient(4, '积极主张', '清晰直接地表达自身立场，通过正面说服和辩论来争取支持。'),
      createGradient(5, '强硬对峙', '直接挑战对方，拒绝让步，通过施加压力或威胁来迫使对方改变。'),
      createGradient(6, '策略操纵', '隐藏真实意图，通过欺骗、误导或情感勒索等非直接手段达成目的。'),
      createGradient(7, '强制执行', '无视对方意愿，利用自身压倒性优势（或在绝望中）单方面强行实现目标。'),
    ],
    subjective_state_options: [
      { level: '', label: '---', description: '请选择一个选项', value: '' },
      { level: '', label: '认同', description: '内心认同当前的权力结构，并将其内化为自我认知的一部分。', value: '认同' },
      { level: '', label: '享受', description: '从当前的权力位置中获得愉悦感或满足感。', value: '享受' },
      { level: '', label: '忍受', description: '不享受但为了更高目标（生存、保护他人等）而有意识地忍耐。', value: '忍受' },
      { level: '', label: '憎恨', description: '内心充满对权力结构或上位者的憎恨与厌恶，但可能未表现出来。', value: '憎恨' },
      { level: '', label: '矛盾', description: '在认同、享受、憎恨等多种情绪之间挣扎，内心充满矛盾。', value: '矛盾' },
      {
        level: '',
        label: '漠然/麻木',
        description: '对权力关系既不接受也不反抗，情感上完全疏离，处于一种麻木或事不关己的状态。',
        value: '漠然/麻木',
      },
    ],
    target_subjective_state_options: [
      { level: '', label: '---', description: '请选择一个选项', value: '' },
      { level: '', label: '无变化', description: '内心状态保持不变，与初始状态相同。', value: '无变化' },
      { level: '', label: '认同', description: '内心认同当前的权力结构，并将其内化为自我认知的一部分。', value: '认同' },
      { level: '', label: '享受', description: '从当前的权力位置中获得愉悦感或满足感。', value: '享受' },
      { level: '', label: '忍受', description: '不享受但为了更高目标（生存、保护他人等）而有意识地忍耐。', value: '忍受' },
      { level: '', label: '憎恨', description: '内心充满对权力结构或上位者的憎恨与厌恶，但可能未表现出来。', value: '憎恨' },
      { level: '', label: '矛盾', description: '在认同、享受、憎恨等多种情绪之间挣扎，内心充满矛盾。', value: '矛盾' },
      {
        level: '',
        label: '漠然/麻木',
        description: '对权力关系既不接受也不反抗，情感上完全疏리，处于一种麻木或事不关己的状态。',
        value: '漠然/麻木',
      },
    ],
  },
  narrative: {
    world_harmony_spectrum: [
      BLANK_GRADIENT_OPTION,
      createGradient(1, '积极敌对', '世界规则有意与玩家作对。'),
      createGradient(2, '漠不关心', '世界冷酷无情，规则严苛。'),
      createGradient(3, '中立现实', '世界按自身逻辑运转。'),
      createGradient(4, '略有偏向', '运气和机遇比不幸多一点。'),
      createGradient(5, '欲望友好', '世界规则引导玩家实现目标。'),
      createGradient(6, '强力辅助', '世界总在关键时刻提供便利。'),
      createGradient(7, '欲望实现机', '世界为满足玩家欲望而存在。'),
    ],
    npc_compliance_spectrum: [
      BLANK_GRADIENT_OPTION,
      createGradient(1, '执拗对抗', '极强独立意志，常与玩家相悖。'),
      createGradient(2, '原则性抵抗', '有底线，不违背原则时才合作。'),
      createGradient(3, '独立自主', '有独立议程，需充分理由才被说服。'),
      createGradient(4, '动态响应', '顺从度取决于玩家的行为和关系。'),
      createGradient(5, '倾向于合作', '更倾向于赞同和配合玩家。'),
      createGradient(6, '被动顺从', '缺乏主见，容易被玩家引导。'),
      createGradient(7, '无条件服从', 'NPC为满足玩家意愿而存在。'),
    ],
    pace_spectrum: [
      BLANK_GRADIENT_OPTION,
      createGradient(1, '生活流', '无关键事件，专注日常氛围。'),
      createGradient(2, '慢热', '节奏缓慢，注重长时间情感铺垫。'),
      createGradient(3, '稳步推进', '事件按部就班，铺垫充足。'),
      createGradient(4, '标准节奏', '张弛有度，平静期与高潮期交替。'),
      createGradient(5, '事件驱动', '由一连串紧凑事件驱动，节奏较快。'),
      createGradient(6, '快节奏', '情节密集，高潮迭起。'),
      createGradient(7, '持续高能', '从头到尾持续紧张与高密度事件。'),
    ],
    perspective_choice: [
      BLANK_GRADIENT_OPTION,
      {
        level: '',
        label: '第一人称（主控角色）',
        description: '以主控角色(PC)的“我”进行叙事，能最深入地体验其内心。',
        value: '第一人称（主控角色）',
      },
      {
        level: '',
        label: '第一人称（指定NPC）',
        description: '以某个重要配角(NPC)的“我”进行叙事，从不同角度揭示故事。',
        value: '第一人称（指定NPC）',
      },
      {
        level: '',
        label: '第一人称复数（我们）',
        description: '以一个集体（如村庄、家庭、小队）的“我们”进行叙事，讲述共同经历。',
        value: '第一人称复数（我们）',
      },
      {
        level: '',
        label: '第二人称（主控角色）',
        description: '以“你”的视角进行叙事，常用于互动小说或指令式体验，默认指代主控角色(PC)。',
        value: '第二人称（主控角色）',
      },
      {
        level: '',
        label: '第三人称限知（主控角色）',
        description: '以“他/她”的视角叙事，但只能了解主控角色的所见所想。',
        value: '第三人称限知（主控角色）',
      },
      {
        level: '',
        label: '第三人称限知（指定NPC）',
        description: '以“他/她”的视角叙事，但只能了解某个特定NPC的所见所想。',
        value: '第三人称限知（指定NPC）',
      },
      {
        level: '',
        label: '第三人称全知',
        description: '上帝视角，可以洞悉所有角色的内心活动和故事全貌。',
        value: '第三人称全知',
      },
    ],
    perspective_switching_mode: [
      BLANK_GRADIENT_OPTION,
      { level: '', label: '严格固定', description: '绝不切换视角。', value: '严格固定' },
      { level: '', label: '情景切换', description: '必要时可短暂切换，之后迅速返回。', value: '情景切换' },
      {
        level: '',
        label: 'POV章节切换',
        description: '以章节或场景为单位，在不同角色视角间切换。',
        value: 'POV章节切换',
      },
    ],
  },
  boundaries: {
    consent_tolerance_level: [
      BLANK_GRADIENT_OPTION,
      createGradient(1, '绝对尊重', '任何行动均需玩家角色明确同意。'),
      createGradient(2, '轻度施压', '可劝说、施加社交压力，无实质强制。'),
      createGradient(3, '情景胁迫', '特定情境下（如被俘）可能被迫选择。'),
      createGradient(4, '心理操纵', '允许欺骗、误导让玩家角色做出违背利益的行动。'),
      createGradient(5, '有限强制', '允许有限的身体冲突或限制自由。'),
      createGradient(6, '核心主题', '允许将“反抗压迫”或“非自愿处境”作为主题。'),
      createGradient(7, '无限制幻想', '允许探索任何形式的违背意愿行为(受Dislikes约束)。'),
    ],
    erotic_level: [
      BLANK_GRADIENT_OPTION,
      { level: '0/6', label: '无', description: '无调情或浪漫互动。', value: '0/6: 无' },
      { level: '1/6', label: '柏拉图式', description: '仅限非身体性的浪漫互动。', value: '1/6: 柏拉图式' },
      { level: '2/6', label: '暗示性', description: '允许调情、暧昧、轻微身体接触。', value: '2/6: 暗示性' },
      { level: '3/6', label: '情感导向', description: '允许基于情感连接的亲密行为。', value: '3/6: 情感导向' },
      {
        level: '4/6',
        label: '愉悦导向',
        description: '允许以纯粹愉悦为目的的多样化亲密行为。',
        value: '4/6: 愉悦导向',
      },
      {
        level: '5/6',
        label: '权力/癖好导向',
        description: '允许包含权力动态、特定癖好等复杂互动。',
        value: '5/6: 权力/癖好导向',
      },
      {
        level: '6/6',
        label: '禁忌/超越性行为',
        description: '允许探索超越常规、带禁忌性质的幻想行为。',
        value: '6/6: 禁忌/超越性行为',
      },
    ],
    erotic_focus: [
      BLANK_GRADIENT_OPTION,
      createFocusGradient(1, '背景式', '相关内容只在情节逻辑上绝对必要时才出现。它服务于故事，但本身不是焦点。'),
      createFocusGradient(2, '点缀式', '相关内容被用作调味剂，以增强氛围、塑造角色或在关键时刻提升情感强度。'),
      createFocusGradient(3, '核心式', '故事积极地寻求并围绕这类内容展开。它是情节的核心驱动力和玩家体验的主要来源。'),
      createFocusGradient(4, '崇尚式', '故事不仅以这类内容为核心，还会对其进行美学化、风格化甚至“赞美”。'),
    ],
    violence_level: [
      BLANK_GRADIENT_OPTION,
      { level: '0/6', label: '无', description: '无身体冲突。', value: '0/6: 无' },
      { level: '1/6', label: '喜剧/仪式性', description: '无实际伤害的冲突。', value: '1/6: 喜剧/仪式性' },
      { level: '2/6', label: '体育/自卫', description: '有规则的搏斗或合理自卫。', value: '2/6: 体育/自卫' },
      { level: '3/6', label: '写实战斗', description: '造成非致命性伤害的战斗。', value: '3/6: 写实战斗' },
      { level: '4/6', label: '致命武力', description: '允许在战斗中杀死敌人。', value: '4/6: 致命武力' },
      { level: '5/6', label: '处决/冷血', description: '允许对无抵抗者使用致命武力。', value: '5/6: 处决/冷血' },
      { level: '6/6', label: '酷刑/虐待', description: '允许以施加痛苦为目的的系统性暴力。', value: '6/6: 酷刑/虐待' },
    ],
    violence_focus: [
      BLANK_GRADIENT_OPTION,
      createFocusGradient(1, '背景式', '相关内容只在情节逻辑上绝对必要时才出现。它服务于故事，但本身不是焦点。'),
      createFocusGradient(2, '点缀式', '相关内容被用作调味剂，以增强氛围、塑造角色或在关键时刻提升情感强度。'),
      createFocusGradient(3, '核心式', '故事积极地寻求并围绕这类内容展开。它是情节的核心驱动力和玩家体验的主要来源。'),
      createFocusGradient(4, '崇尚式', '故事不仅以这类内容为核心，还会对其进行美学化、风格化甚至“赞美”。'),
    ],
    description_intensity_spectrum: [
      BLANK_GRADIENT_OPTION,
      createGradient(1, '完全回避', '事件发生但不描写 (“拉灯”)。'),
      createGradient(2, '抽象暗示', '使用比喻、意象等间接手法。'),
      createGradient(3, '侧重感受', '描写角色的主观感受和情绪。'),
      createGradient(4, '简略写实', '以简洁、客观的语言概括性描述。'),
      createGradient(5, '细节描绘', '对关键动作和细节进行生动、具体描绘。'),
      createGradient(6, '直白露骨', '使用非常直白的语言详细描写。'),
      createGradient(7, '临床级详尽', '极度逼真、不加修饰的细节描写。'),
    ],
    consequence_severity_spectrum: [
      BLANK_GRADIENT_OPTION,
      createGradient(1, '无后果', '选择无负面影响。'),
      createGradient(2, '可轻易逆转', '后果很小，可轻松挽回。'),
      createGradient(3, '低风险', '后果造成暂时不便，不影响主线。'),
      createGradient(4, '中等风险', '后果可能锁定剧情，但可弥补。'),
      createGradient(5, '高风险', '后果严重，可能导致NPC死亡或任务永久失败。'),
      createGradient(6, '永久性改变', '后果永久性地改变角色或世界，不可逆。'),
      createGradient(7, '游戏结束', '错误决定导致故事灾难性提前结束。'),
    ],
  },
};
