export const PRESET_TYPE_OPTIONS: Record<string, { value: string; label: string }[]> = {
  event: [
    { value: 'power_shift', label: '权力更迭' },
    { value: 'catastrophe', label: '大灾难' },
    { value: 'discovery', label: '重大发现' },
    { value: 'social_change', label: '社会变革' },
    { value: 'alliance_split', label: '联盟/分裂' },
    { value: '', label: '其他/自定义/空白' },
  ],
  era: [
    { value: 'origin', label: '起源/开端时代' },
    { value: 'golden', label: '繁荣/黄金时代' },
    { value: 'chaos', label: '动荡/黑暗时代' },
    { value: 'recovery', label: '复兴/重建时代' },
    { value: 'transition', label: '沉寂/过渡时代' },
    { value: '', label: '其他/自定义/空白' },
  ],
  species: [
    { value: 'main', label: '主流族群' },
    { value: 'minority', label: '亚种/少数族群' },
    { value: 'intelligent', label: '智慧生物' },
    { value: 'hybrid', label: '变异/混血种群' },
    { value: '', label: '其他/自定义/空白' },
  ],
  location: [
    { value: 'power_center', label: '权力中心' },
    { value: 'residential', label: '普通聚居区' },
    { value: 'wilderness', label: '边缘/荒野区域' },
    { value: 'hub', label: '交通枢纽' },
    { value: 'landmark', label: '重要建筑/遗迹' },
    { value: 'special', label: '特殊空间' },
    { value: '', label: '其他/自定义/空白' },
  ],
  powersystem: [
    { value: 'magic', label: '魔法体系' },
    { value: 'cultivation', label: '修行体系' },
    { value: 'divine', label: '信仰/神力体系' },
    { value: 'bloodline', label: '血统/天赋能力' },
    { value: 'spirit', label: '灵魂/精神力量' },
    { value: '', label: '其他/自定义/空白' },
  ],
  item: [
    { value: 'weapon', label: '武器/法器' },
    { value: 'armor', label: '防具/护具' },
    { value: 'tool', label: '工具/装置' },
    { value: 'consumable', label: '消耗品/药剂' },
    { value: 'relic', label: '神秘遗物/奇物' },
    { value: '', label: '其他/自定义/空白' },
  ],
  tech: [
    { value: 'transport', label: '交通/通讯技术' },
    { value: 'energy', label: '能源/动力系统' },
    { value: 'medical', label: '医疗/生物技术' },
    { value: 'ai', label: '信息/人工智能' },
    { value: 'weapon_system', label: '武器/防御系统' },
    { value: 'industry', label: '工业/生产设备' },
    { value: '', label: '其他/自定义/空白' },
  ],
  faction: [
    { value: 'ruler', label: '统治阶层/政权' },
    { value: 'religion', label: '宗教/信仰团体' },
    { value: 'business', label: '商业/经济组织' },
    { value: 'secret', label: '秘密结社/地下势力' },
    { value: 'military', label: '军事/武装团体' },
    { value: 'academy', label: '学术/修行团体' },
    { value: '', label: '其他/自定义/空白' },
  ],
  resource: [
    { value: 'energy', label: '能源/灵力源' },
    { value: 'metal', label: '稀有金属/矿产' },
    { value: 'material', label: '魔法/修行材料' },
    { value: 'knowledge', label: '信息/知识' },
    { value: 'currency', label: '货币/流通物' },
    { value: '', label: '其他/自定义/空白' },
  ],
  belief: [
    { value: 'mainstream', label: '主流信仰/官方宗教' },
    { value: 'plural', label: '多元信仰/哲学流派' },
    { value: 'pragmatic', label: '实用主义/无神论' },
    { value: 'heretic', label: '边缘/异端思想' },
    { value: '', label: '其他/自定义/空白' },
  ],
  custom: [
    { value: 'festival', label: '重要节日/庆典' },
    { value: 'rite', label: '成年礼/转变仪式' },
    { value: 'marriage', label: '婚丧嫁娶' },
    { value: 'etiquette', label: '日常礼仪/禁忌' },
    { value: 'special', label: '特殊仪式' },
    { value: '', label: '其他/自定义/空白' },
  ],
  class: [
    { value: 'upper', label: '上层阶级/统治者' },
    { value: 'middle', label: '中产/自由民' },
    { value: 'lower', label: '底层/被压迫群体' },
    { value: 'marginal', label: '边缘/流浪者' },
    { value: '', label: '其他/自定义/空白' },
  ],
  desire_element: [
    { value: 'norm', label: '社会规范/禁忌' },
    { value: 'power', label: '权力/地位相关' },
    { value: 'love', label: '爱情/亲密关系' },
    { value: 'supernatural', label: '超自然/特殊情欲' },
    { value: '', label: '其他/自定义/空白' },
  ],
};
